# version: '3.7'
services:
    app:
        build: .
        container_name: "php74-1"
        # container_name: "gallant_kepler"
        volumes:
            - "./app/:/var/www/html"
            # - "./config/apache/httpd.conf:/etc/apache2/apache2.conf"
        privileged: true
        ports:
            - "80:80"
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        volumes:
            - ./config/mysql/data:/var/lib/mysql
            - ./config/mysql/mycnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_DATABASE=ocha
            - MYSQL_USER=ochauser
            - MYSQL_PASSWORD=ochapassword
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "4306:3306"
        container_name: mysql8-1
        # container_name: ocha-mysql